### ISSUE TITLE
Ollama Support for Local LLM Inferencing

### ISSUE THREAD

**Issue by kb14** [PySpur-Dev/PySpur#54]
Hey Pyspur team!

Great product, love it!  Would be great to have Ollama support for local development. 

Why Ollama:
- Local development & testing without racking up API costs :)
- Access to open-source models (Llama, Mistral, etc.)
- Similar API structure to OpenAI 

Happy to help with implementation if needed.

**Comment by srijanpatel** [comment]
Thanks for raising this @kb14 
We are working on Ollama support currently. 
Would you be willing to review the changes and test it when done?

I'll keep this thread updated with the progress.

**Comment by kb14** [comment]
Happy to test @srijanpatel . Guess #55  completes it?
